# Generated by Django 4.2.3 on 2023-08-01 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0002_result_remove_conceptual_well_formed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportUserStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "recommendation",
                    models.CharField(blank=True, max_length=400, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "userstory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inputUS.userstory_element",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report User Story",
                "verbose_name_plural": "Report User Story",
            },
        ),
    ]
