# Generated by Django 4.2.3 on 2023-08-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0003_reportuserstory"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportuserstory",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Well Formed"),
                    (2, "Atomicity"),
                    (3, "Precise Criteria"),
                    (4, "Consistent Criteria"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness Criteria"),
                ],
                null=True,
            ),
        ),
    ]
