# Generated by Django 4.2.3 on 2023-08-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0004_reportuserstory_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory_element",
            name="is_problem",
            field=models.BooleanField(default=False),
        ),
    ]
