# Generated by Django 4.2.3 on 2023-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0005_userstory_element_is_problem"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportuserstory",
            name="is_problem",
            field=models.BooleanField(default=False),
        ),
    ]
