# Generated by Django 4.2.3 on 2023-08-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0006_reportuserstory_is_problem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportuserstory",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Well Formed"),
                    (2, "Atomicity"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
    ]
