# Generated by Django 4.2.3 on 2023-08-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0008_userstory_element_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportuserstory",
            name="recommendation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
