# Generated by Django 4.2.3 on 2023-08-24 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inputUS", "0009_alter_reportuserstory_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_create_by_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dibuat Oleh",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="reportuserstory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="reportuserstory",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_create_by_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dibuat Oleh",
            ),
        ),
        migrations.AddField(
            model_name="reportuserstory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="us_upload",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="us_upload",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_create_by_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dibuat Oleh",
            ),
        ),
        migrations.AddField(
            model_name="us_upload",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userstory_element",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="userstory_element",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_create_by_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Dibuat Oleh",
            ),
        ),
        migrations.AddField(
            model_name="userstory_element",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
