# Generated by Django 4.2.3 on 2023-08-24 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inputUS", "0011_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_create_by_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "keyword",
                    models.ManyToManyField(blank=True, to="inputUS.keywordglossary"),
                ),
                (
                    "report",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inputUS.reportuserstory",
                    ),
                ),
                ("roles", models.ManyToManyField(blank=True, to="inputUS.role")),
            ],
            options={
                "verbose_name": "Report Terms",
                "verbose_name_plural": "Report Terms",
            },
        ),
    ]
