# Generated by Django 4.2.3 on 2023-08-24 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0012_reportterms"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportterms",
            name="report",
        ),
        migrations.AddField(
            model_name="reportterms",
            name="userstory",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inputUS.userstory_element",
            ),
        ),
    ]
