# Generated by Django 4.2.3 on 2023-08-24 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0013_remove_reportterms_report_reportterms_userstory"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportterms",
            name="glossarys",
            field=models.ManyToManyField(to="inputUS.glossary"),
        ),
        migrations.RemoveField(
            model_name="reportterms",
            name="keyword",
        ),
        migrations.AlterField(
            model_name="reportterms",
            name="roles",
            field=models.ManyToManyField(to="inputUS.role"),
        ),
        migrations.AlterField(
            model_name="reportterms",
            name="userstory",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inputUS.userstory_element",
            ),
        ),
        migrations.AddField(
            model_name="reportterms",
            name="keyword",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inputUS.keywordglossary",
            ),
        ),
    ]
