# Generated by Django 4.2.3 on 2023-08-24 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0014_reportterms_glossarys_remove_reportterms_keyword_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportterms",
            name="roles",
        ),
        migrations.AddField(
            model_name="role",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inputUS.project",
            ),
        ),
    ]
