# Generated by Django 4.2.3 on 2023-08-24 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0016_remove_reportterms_glossarys_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="project",
        ),
        migrations.AddField(
            model_name="role",
            name="userstory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inputUS.userstory_element",
            ),
        ),
    ]
