# Generated by Django 4.2.3 on 2023-08-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0017_remove_role_project_role_userstory"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory_element",
            name="old_userstory",
            field=models.CharField(max_length=800, null=True),
        ),
    ]
