# Generated by Django 4.2.3 on 2023-09-06 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0018_userstory_element_old_userstory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstory_element",
            name="What_full",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inputUS.userstory_what",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstory_element",
            name="Who_full",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inputUS.userstory_who",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userstory_element",
            name="Why_full",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inputUS.userstory_why",
            ),
            preserve_default=False,
        ),
    ]
