# Generated by Django 4.2.3 on 2023-09-06 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inputUS", "0021_alter_userstory_element_what_full_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessBackground",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("percentage", models.CharField(max_length=7, null=True)),
                ("is_process", models.BooleanField(default=False)),
                ("is_done", models.BooleanField(default=False)),
                ("description", models.TextField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_create_by_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                ("userstorys", models.ManyToManyField(to="inputUS.userstory_element")),
            ],
            options={
                "verbose_name": "Process Background",
                "verbose_name_plural": "Process Background",
            },
        ),
    ]
