# Generated by Django 4.2.3 on 2023-09-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0024_reportterms_edit_adjusteduserstory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reportterms",
            name="edit",
        ),
        migrations.AddField(
            model_name="reportuserstory",
            name="edit",
            field=models.IntegerField(
                choices=[
                    (1, "Action"),
                    (2, "Role"),
                    (3, "Action and Role"),
                    (4, "None"),
                ],
                null=True,
            ),
        ),
    ]
