# Generated by Django 4.2.3 on 2023-09-11 10:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0025_remove_reportterms_edit_reportuserstory_edit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reportuserstory",
            old_name="edit",
            new_name="recommendation_type",
        ),
    ]
