# Generated by Django 4.2.3 on 2023-09-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0027_role_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportuserstory",
            name="recommendation_type",
            field=models.IntegerField(
                choices=[
                    (1, "Action"),
                    (2, "Role"),
                    (3, "Action and Role"),
                    (4, "None"),
                    (5, "Action Manual"),
                ],
                null=True,
            ),
        ),
    ]
