# Generated by Django 4.2.3 on 2023-09-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0028_alter_reportuserstory_recommendation_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportuserstory",
            name="predicate",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="reportuserstory",
            name="subject",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
