# Generated by Django 4.2.3 on 2023-09-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0030_role_role_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="us_upload",
            name="is_show",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="adjusteduserstory",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Well Formed"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reportterms",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Well Formed"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reportuserstory",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Well Formed"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Well Formed"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
    ]
