# Generated by Django 4.2.3 on 2023-09-21 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inputUS", "0031_us_upload_is_show_alter_adjusteduserstory_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adjusteduserstory",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Well-Formedness"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reportterms",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Well-Formedness"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reportuserstory",
            name="type",
            field=models.IntegerField(
                choices=[
                    (1, "Well-Formedness"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Well-Formedness"),
                    (2, "Atomicity"),
                    (7, "Conciseness"),
                    (3, "Preciseness"),
                    (4, "Consistency"),
                    (5, "Conceptually Sound"),
                    (6, "Uniqueness"),
                ],
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="NameFileUsed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_create_by_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Dibuat Oleh",
                    ),
                ),
                (
                    "name_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inputUS.us_upload",
                    ),
                ),
            ],
            options={
                "verbose_name": "Name File Used",
                "verbose_name_plural": "Name File Used",
            },
        ),
    ]
