# Generated by Django 4.2.3 on 2023-10-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0033_reportterms_problem_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportterms",
            name="sbar_text",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
