# Generated by Django 4.2.3 on 2023-10-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0035_personas"),
    ]

    operations = [
        migrations.AddField(
            model_name="personas",
            name="key_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
