# Generated by Django 4.2.3 on 2023-11-28 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inputUS", "0037_reportuserstory_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstory_element",
            name="is_agree",
            field=models.BooleanField(default=False),
        ),
    ]
