# Generated by Django 4.2.3 on 2026-01-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inputUS", "0039_reportuserstory_disagree_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportuserstory",
            name="userstory_unique",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="userstory_uniquex",
                to="inputUS.userstory_element",
            ),
        ),
    ]
